### ISSUE TITLE
Does test environment support MobilePay?

### ISSUE THREAD

**Issue by mindtheworld** [DIBS-Payment-Services/Easy-Android-SDK#16]
I've tried to test out 'MobilePay' option, but got 500 with below error message:
![image](https://user-images.githubusercontent.com/34175635/140753548-de51e93b-2cdb-4289-ace6-b12f06df90e3.png)

HostedPaymentPageUrl: 
https://test.checkout.dibspayment.eu/hostedpaymentpage/?checkoutKey=9966bca917184b0f89ed39a8d0839bcb&pid=01400000618921aa4b72bbc335aa7e1a

Request Url: https://test.checkout.dibspayment.eu/api/v1/pay

Request Payload:
![image](https://user-images.githubusercontent.com/34175635/140753984-a0ab6638-fdb7-4b89-8500-c0d9737ada6f.png)

**Comment by Nets-in-app** [comment]
Hello @mindtheworld ,

Unfortunately, the mobilepay test environment is not supported. Please try to use your production mobilepay account instead.

**Comment by mindtheworld** [comment]
Hej @Nets-in-app 

What do you mean by 'production mobilepay account'? should I configure it in 'portal.dibspayment.eu', or it will work automatically in production env?

**Comment by Nets-in-app** [comment]
HI @mindtheworld ,

MobilePay has both test App(https://developer.mobilepay.dk/products/online/test) and production App downloading directly from play store. Nets Easy only support Mobilepay production app. Could you please let us know which mobilepay app are you using and please try to use mobilepay production app to have a try if you used the test one? 

In addition, if it doesn't help, we need to check if your account enables the mobilepay as the supported payment method. Please raise the issue directly to corresponding our customer support listed below.

Norway
Telephone: +47 815 00 545
E-Mail: ecom-no@nets.eu 

Denmark
Telephone: +45 88 777 013
E-Mail: ecom-dk@nets.eu 

Sweden
Telephone: +46 (0)8 609 92 00
E-Mail: ecom-se@nets.eu

Finland
Telephone: +358 10 80 40 40
E-Mail: ecommerce-support-fi@nets.eu 

Germany
Telephone: +49 69 7922 2567
E-Mail: ecom-de@nets.eu 

Austria
Telephone: +43 0800 100 320
E-Mail: ecom-de@nets.eu

**Comment by mindtheworld** [comment]
Tested with production mobilepay account, works fine.
